import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
      <Container>
      <Title>MKS</Title>
      <Text>Sistemas</Text>
      <Button>
        <i className="fa-solid fa-bag-shopping"></i>
        <span className="btn-cart-badge"></span>
      </Button>
      </Container>
    </Header>

    <Main>

    </Main>

      <Footer>
        <P>
          MKS sistemas © Todos os direitos reservados
        </P>
      </Footer>
    </div>
  )
}

export default Home

const Header = styled.header`
  display: flex;
  background: #0F52BA;
  width: 100%;
  padding: 0 2rem;
`;
const Container = styled.div`
  display: grid;
  grid-template-columns: auto auto auto;
  text-align: center;
  align-items: center;
`;
const Title = styled.h1`
  position: absolute;
  left: 4.51%;
  right: 86.6%;
  font-family: 'Montserrat', sans-serif;
  font-style: normal;
  font-weight: 600;
  font-size: 40px;
  line-height: 19px;
`;
const Text = styled.p`
margin-left: 160px;
padding-top: 0.5rem;
font-family: 'Montserrat', sans-serif;
font-style: normal;
font-weight: 300;
font-size: 20px;
line-height: 19px;
`;
const Button = styled.button`
  width: 90px;
  height: 45px;
  background: #FFFFFF;
  cursor: pointer;
  border-radius: 8px;
  text-align: center;
  margin-left: 1050px;
  margin-right: 50px;
`;
const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`
const Footer = styled.footer`
  display: flex;
  flex: 1;
  height: 34px;
  padding: 2rem 0;
  background:  #EEEEEE;
  justify-content: center;
  align-items: center;
`;
const P = styled.p`
  display: flex;
  justify-content: center;
  align-items: center;
  flex-grow: 1;
  color: #000000;
  font-family: 'Montserrat', sans-serif;
  font-style: normal;
  font-weight: 400;
  font-size: 12px;
  line-height: 15px;
`

